services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=modulith'
      - 'POSTGRES_PASSWORD=modulithdb'
      - 'POSTGRES_USER=modulithdb'
    ports:
      - '5432:5432'
    volumes:
      - /Users/hectordelgado/Documents/dev/tmp/postgres_modulith:/var/lib/postgresql/data

volumes:
  postgres:
